a = input('Digite algo: ')
print('O tipo primitivo é: ', type(a))
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Está em letras minúsculas?', a.islower())
print('É decimal?', a.isdecimal())
print('Está em letras maiúsculas?', a.isupper())
print('É um espaço em branco?', a.isspace())
print('Está na tabela ASCII?', a.isascii())
print('Está capitalizado?', a.istitle())
